### ISSUE TITLE
List of issues and thoughts.

### ISSUE THREAD

**Issue by gotex007** [CharlieBaird/PoECraftingAssistant#13]
After looking through the Reddit thread and taking a look at the program I have a series of thoughts and nitpicks. I really do want this tool to be great. It might actually get me to craft for the first time (I've technically played since 2013 but only _really_ since Legion) and with the upcoming crafting league, I can only hope it's up to my expectations by then (though next league would be more likely I think).

Issues:
1. The weird issue with error of not being able to copy the item initially. You addressed it in the thread, but it is annoying.
2. Trying to ctrl+A while searching modifiers fails. It highlights it and quickly unhighlights it for some reason so you have to be fast to erase it.
3. I noticed this modifier is missing while testing: Players cannot Regenerate Life, Mana or Energy Shield

Nitpicks:
1. It feels awkward to have to click in the box to start typing when I already clicked to add a modifier in the first place. Defaulting the cursor to the dropdown box would be nice.
2. The sound when you "hit" is subtle and quiet. I think should be able to pick the volume and sound played, even if this means manually replacing a sound file in the files.
3. It might be because of the sound and how it the audio itself starts up but it feels delayed in alerting me and I have already straight up rolled over a "hit" without me even going that fast. I did try playing with the delay but it didn't change anything from my perspective.
4. I know you're afraid of violating ToS but I don't think we should have to rely solely on a sound. Maybe some kind of visual cue with a tooltip attached to the mouse or something as well.
5. I couldn't find a way to search for either or but not both. If I could at least search for a maximum count of modifiers that would do it, but there's only the option for a minimum. An example I've done in the past is being okay with increased life and with increased elemental resistance on monsters but not both because that made the blighted map too difficult for me. Or being okay with 1 source of monsters deal X type of additional damage but not several sources.
6. I can't tell how I'm supposed to save the filter. I can tell how to open a saved one though.
7, It'd be nice if clicking outside of the dialogue box when selecting a mod was the equivalent of hitting the X button to close it instead of windows yelling at me. Not the most important though.

**Comment by CharlieBaird** [comment]
Thanks for compiling this list. Some of these bugs/features are already being looked at, but many are not. I'll look into these issues tomorrow, it's been a long day.
By the way, the tool automatically saves every change you make to the filter on each button press. You shouldn't have to worry about saving, it does it for you. Although I may add a button or an indicator that it has been saved.
I hope to have a somewhat polished version released by league start. I've been pulling some crazy hours trying to make this happen 👍

**Comment by gotex007** [comment]
I appreciate the effort and was just talking about wishing we had some tool or something like this yesterday with a friend of mine. I've never been able to really get into crafting. This would help a lot.

I do think we should be able to save and load separate filters though.

**Comment by CharlieBaird** [comment]
> I do think we should be able to save and load separate filters though.

Right, sorry I should rephrase: This is already implemented, it autosaves the current filter you are working on. Clicking "folder" in the top left lets you view the list of your filters, and "New" creates a new filter. The old one you were working on is automatically saved and can be reopened by clicking "open."

**Comment by CharlieBaird** [comment]
Everything here has been addressed, thanks again. Will be available with the next release.
