### ISSUE TITLE
 roll-overs prevention suggestion

### ISSUE THREAD

**Issue by Shidzy** [CharlieBaird/PoECraftingAssistant#16]
I already see you have this in requests:
Request: Create a popup when it hits the filter to prevent roll-overs. This will be toggleable

I think this should be №1 feature(killer feature), also what i can suggest - maybe if it possible even disable mouse clicks at all

**Comment by CharlieBaird** [comment]
Thanks for the request; I'm still brainstorming alternatives to this solution. From what I know, I cannot disable the mouse input because that would require hooking into the native OS. I'll update you when I get on this.

**Comment by CharlieBaird** [comment]
This has been added. It will be released along with the official version in a few days.
